### ISSUE TITLE
Dashboard Preview- Console Error 401 for unowned data-set

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1061]
Commit: 561ef26272fb221416e38e5473f1bed7b913601e
### Steps to reproduce
1. Login to the stem cell common instance
2. Preview a public file (you don't own)
### Observed behavior

Preview shows correctly but there's  a console error.
Request:
`Request URL:https://refinery-dev.stemcellcommons.org/api/v1/data_sets/781dbf25-2ab7-41a9-953c-6bbed44e5c8e/sharing/?format=json
Request Method:GET
Status Code:401 UNAUTHORIZED
Remote Address:140.247.151.105:443`

Console.error:
`angular.js:10967 GET https://refinery-dev.stemcellcommons.org/api/v1/data_sets/781dbf25-2ab7-41a9-953c-6bbed44e5c8e/sharing/?format=json 401 (UNAUTHORIZED)`
### Expected behavior

No Console Error.

**Comment by flekschas** [comment]
This is not a bug because Angular always logs errors on the console by default and the 401 is expected. I wouldn't want to suppress HTTP return codes, instead we could implement a custom log decorator and send logs somewhere other than the console.

https://stackoverflow.com/questions/28682711/angular-logs-error-to-console-before-raising-promise-catch
https://stackoverflow.com/questions/22113286/prevent-http-errors-from-being-logged-in-browser-console

**Comment by flekschas** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;OPb9nd2Z&#x2F;102-global-error-handling-and-displaying-for-the-ui"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Global error handling and displaying for the UI.</a>
