### ISSUE TITLE
Rewrite analysis_manager.views.get_full_url() to make it reusable

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1063]
This function takes a FileStoreItem instance which leads to code duplication and limited reuse potential. It should take a relative URL instead which would make it usable for creating registration and data set sharing URLs as well.

Options to determine whether http or https URL should be returned:
* https://docs.djangoproject.com/en/1.9/ref/request-response/#django.http.HttpRequest.build_absolute_uri
* https://docs.djangoproject.com/en/1.9/ref/request-response/#django.http.HttpRequest.is_secure
* https://docs.python.org/2/library/wsgiref.html#wsgiref.util.guess_scheme
* http://wsgi.readthedocs.io/en/latest/definitions.html#envvar-wsgi.url_scheme - https://www.python.org/dev/peps/pep-0333/#url-reconstruction
* Django setting (e.g., `REFINERY_URL_SCHEME = "https"`) - https://fragmentsofcode.wordpress.com/2009/02/24/django-fully-qualified-url/
* https://github.com/parklab/refinery-platform/blob/develop/refinery/templates/registration/password_reset_email.html

**Comment by scottx611x** [comment]
**These both require an `HttpRequest` object, whereas we are currently dealing with `relative_url`s as strings**
- https://docs.djangoproject.com/en/1.9/ref/request-response/#django.http.HttpRequest.build_absolute_uri 
- https://docs.djangoproject.com/en/1.9/ref/request-response/#django.http.HttpRequest.is_secure

**These may be good for the future when we actually implement SSL**
- https://docs.python.org/2/library/wsgiref.html#wsgiref.util.guess_scheme
- http://wsgi.readthedocs.io/en/latest/definitions.html#envvar-wsgi.url_scheme
- https://www.python.org/dev/peps/pep-0333/#url-reconstruction

**This way is simple enough and it make it clear as to/easy to find what protocol we are using since this change exists with all of our other settings**
- https://fragmentsofcode.wordpress.com/2009/02/24/django-fully-qualified-url/

I've currently implemented the last item in the list to take care of construction of our full urls, but the middle 3 links will help out later on.

**Comment by scottx611x** [comment]
@hackdna Should this be closed for now, and should the suggestions here be looked at in issue: #318

**Comment by scottx611x** [comment]
This can be closed upon merging: #1092
