### ISSUE TITLE
Problem loading tab delimited metadata file generated as output from R

### ISSUE THREAD

**Issue by sjhosui** [parklab/refinery-platform#1252]
Commit:

### Steps to reproduce
1. Tried to load the attached file. The first column heading is missing (this is the default behaviour for writing an object out to file in R). 
[Mov10_full_meta.txt](https://github.com/parklab/refinery-platform/files/370073/Mov10_full_meta.txt)

### Observed behavior

Doesn't display table but looks like it is loading it - headings are shown in the "Source Index Column" input box.

![screen shot 2016-07-18 at 4 30 19 pm](https://cloud.githubusercontent.com/assets/697229/16929277/f5fa5648-4d04-11e6-8ef9-ea9f522795f0.png)

### Expected behavior
Should load the preview correctly.

**Comment by hackdna** [comment]
The issue is caused by extra tab characters at the beginning and the end of the header row in the metadata file. We should remove extra tab characters using the [d3.tsv API](https://github.com/d3/d3-request/blob/master/README.md#tsv). An additional example: http://www.d3noob.org/2012/12/getting-data.html.
