### ISSUE TITLE
Permission Editor not available for unshared data sets

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1315]
Commit: 33de42c5dcd1e22fe17e4

### Steps to reproduce
- Go to a data set which you own and which is not shared
- Click Share

### Observed behavior
The dialog has no options, and only a cancel button

### Expected behavior
- There should either be some explanation
- Or I should not be able to bring up this dialog in the first place

<img width="621" alt="screen shot 2016-08-08 at 5 00 55 pm" src="https://cloud.githubusercontent.com/assets/730388/17496094/b892c8a4-5d89-11e6-9566-c12e26c0d0c1.png">

**Comment by ngehlenborg** [comment]
Is suspect that you were not member of any group - can you confirm that? In principle, the `Public` group should always show up here but I guess due to #1304 you were able to leave that group.

But I agree that a message should be shown, e.g. "You are not member of any groups. Data sets can only be shared with groups that you are a member of.".

**Comment by mccalluc** [comment]
@nils: No, this is the "mccalluc2" account, which is a member of "Public" and "Refinery Developers". I've checked the four data sets which are owned by me and not shared with a group, and they all present this same empty dialog when I click "share"

**Comment by ngehlenborg** [comment]
Addressed by d96ff9205611210e71e0ef42f20d101827a17bab.
