### ISSUE TITLE
Analysis Redirect UI Bug 

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1415]
https://www.evernote.com/shard/s59/sh/3819898f-5e8f-4378-b17f-4363aab950df/96bb4f715fec660e

<img width="748" alt="screen shot 2016-09-20 at 1 42 35 pm" src="https://cloud.githubusercontent.com/assets/9956764/18681920/20e0a8a2-7f38-11e6-9067-41c6d879c150.png">

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;HVI7HVTY&#x2F;302-spurious-message-about-user-profile"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> spurious message about user profile</a>

**Comment by jkmarx** [comment]
I can not reproduce this issue.

**Comment by ngehlenborg** [comment]
I can't reproduce this issue either right now, but the source of the problem is here:

https://github.com/parklab/refinery-platform/blob/develop/refinery/templates/core/data_set.html#L125

Originally, we inserted status messages on completed analyses (success or failure) into the file browser via Django messages (must be https://docs.djangoproject.com/en/1.10/ref/contrib/messages/). I don't think we are using this any longer (@jkmarx: correct?) and could remove the whole block from the template.

The styling in the issue see in the screenshot above is because there is no "status" information in the message that the registration modules sends.
