### ISSUE TITLE
Prototype of automatic deployment to AWS

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#420]
Run everything in a single EC2 instance in a VPC
using CloudFormation with cfn-pyplates and CodeDeploy

Requires dividing Puppet manifest into separate blocks (classes) to be used depending on the VM/instance configuration.

see also: #416, #418, #774, #779

**Comment by ngehlenborg** [comment]
@drj11: Do you think you have any spare cycles to work on this in the next few weeks? @hackdna has a couple of other big ticket items to work on.

**Comment by drj11** [comment]
yes, definitely. I already am, so assign me.

**Comment by drj11** [comment]
[ ] Work on amazon with separate `.pp` file https://github.com/parklab/refinery-platform/pull/798
[ ] Split `.pp` files so that most of it is shared, with small blocks for each of Vagrant and AWS
[ ] Template `apache.conf` (and share)
[ ] Template `config.json` (note: might all change anyway)

[ ] Separate RDS instance
[ ] Separate EBS

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;OejRcN0q&#x2F;15-implement-single-instance-aws-deployment"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> implement single instance AWS deployment</a>

**Comment by hackdna** [comment]
Thanks @drj11, looks good. I'm going to open a new issue for separating EBS and RDS, and making the Puppet manifest and templates reusable.
