### ISSUE TITLE
Dialog box pops up saying canceling analysis failed when user cancels analysis

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#428]
### Steps to reproduce:
1. Start analysis
2. Click cancel analysis button

### Observed results:
A modal dialog box pops up saying analysis cancellation failed.

### Expected results:
Notification that analysis has been cancelled successfully.

Relevant code:
analysis_manager.views
analysis_monitor.js:
AnalysisMonitor.prototype.cancelAnalysis = function(successCallback,errorCallback)
analysis_status.html:119

**Comment by jkmarx** [comment]
Ajax was interpreting the API success response as an error response because it was expecting a json response and could not parse it. Removed dataType option in Ajax call for cancelAnalysis. 
http://stackoverflow.com/questions/16012815/jquery-ajax-200-ok-json-parseerror
http://stackoverflow.com/questions/25173727/syntax-error-unexpected-end-of-input-parsejson
