### ISSUE TITLE
Upgrade Solr from version 4.4.0 to 5.x

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#457]

**Comment by ngehlenborg** [comment]
@flekschas: any reason why we shouldn't be doing this?

**Comment by flekschas** [comment]
I might be wrong but there could be compatibility issues with Django Haystack. Also, we need to check which changes have been introduced by Solr since 4.x. I can look into this at some point.

**Comment by flekschas** [comment]
Major changes: https://cwiki.apache.org/confluence/display/solr/Major+Changes+from+Solr+4+to+Solr+5
- We'd need to check how Haystack configures Solr because the doc mentions a new way of configuring cores called "Core Discovery", which is optional in v4 but mandatory in v5.
- Solr is now distributed as a stand alone server and should be run as service. When we upgrade we might need to change the supervisor part of Solr.
- Other things seem to be improvements or new features but nothing that cuts compatibility. Even the index of v4 might work fine in v5.

Upgrade instructions:
https://cwiki.apache.org/confluence/display/solr/Upgrading+a+Solr+4.x+Cluster+to+Solr+5.0

**Comment by ngehlenborg** [comment]
Do you want to try to update locally and test? Btw, there is a more recent Haystack (and pysolr) release that should work for us (last time we tried to install them we accidentally installed the latest Django which should not be required).

**Comment by flekschas** [comment]
I can look into that. I think the only crucial thing I need to figure out first is this new configuration.

**Comment by flekschas** [comment]
Close #20bd34c7b3716f2cee6aefa4df29ca610c65a808
