### ISSUE TITLE
Lots of ERROR logs from the status tool

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#518]
In `/vagrant/refinery/log/refinery.log`
```
ERROR    tasks check_tool_status: GALAXY's database entry hasn't been updated since 2015-06-11 17:45:02.099118; check to see if it's running
```
This error is logged twice every second.

**Comment by ngehlenborg** [comment]
@psm3426: I thought we had put something in place that would prevent this message from being logged more than once. Can you comment?

**Comment by psm3426** [comment]
I think something changed in the code to take out the log checking part.  What's written in the current check_tool_status task looks a little different from what I remember.

It's also possible that we didn't actually roll that change in since it would require a database migration to add a boolean field to the ExternalToolStatus model that we'd flip to make note that we don't want to continue to log errors for that tool status until it's been restored to a 'SUCCESS' status.

**Comment by ngehlenborg** [comment]
Closed by removal of ExternalToolStatus backend in e3d48712c4c1fcf87f3e5aa2cc7eec22245b0d04.
