### ISSUE TITLE
Upgrade to Django 1.6

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#612]
Django 1.5 is not supported (no longer receives security updates or bug fixes)
https://docs.djangoproject.com/en/1.6/releases/

**Comment by hackdna** [comment]
Django upgrade cannot happen without rewriting all of the analysis execution/monitoring functionality in Refinery: v1.6 is incompatible with django-celery which is impossible to upgrade without upgrading Celery to v3 which we cannot do without analysis rewrite.

**Comment by scottx611x** [comment]
**Deprecation checks for upgrading to Django 1.6**

- [ ] django.contrib.databrowse will be removed.
- [ ] django.contrib.localflavor will be removed following an accelerated deprecation.
- [ ] django.contrib.markup will be removed following an accelerated deprecation.
- [ ] The compatibility modules django.utils.copycompat and django.utils.hashcompat as well as the functions django.utils.itercompat.all and django.utils.itercompat.any will be removed. The Python builtin versions should be used instead.
- [ ] The csrf_response_exempt and csrf_view_exempt decorators will be removed. Since 1.4 csrf_response_exempt has been a no-op (it returns the same function), and csrf_view_exempt has been a synonym for django.views.decorators.csrf.csrf_exempt, which should be used to replace it.
- [ ] The django.core.cache.backends.memcached.CacheClass backend was split into two in Django 1.3 in order to introduce support for PyLibMC. The historical CacheClass will be removed in favor of django.core.cache.backends.memcached.MemcachedCache.
- [ ] The UK-prefixed objects of django.contrib.localflavor.uk will only be accessible through their GB-prefixed names (GB is the correct ISO 3166 code for United Kingdom).
- [ ] The IGNORABLE_404_STARTS and IGNORABLE_404_ENDS settings have been superseded by IGNORABLE_404_URLS in the 1.4 release. They will be removed.
- [ ] The form wizard has been refactored to use class-based views with pluggable backends in 1.4. The previous implementation will be removed.
- [ ] Legacy ways of calling cache_page() will be removed.
- [ ] The backward-compatibility shim to automatically add a debug-false filter to the 'mail_admins' logging handler will be removed. The LOGGING setting should include this filter explicitly if it is desired.
- [ ] The builtin truncation functions django.utils.text.truncate_words() and django.utils.text.truncate_html_words() will be removed in favor of the django.utils.text.Truncator class.
- [ ] The GeoIP class was moved to django.contrib.gis.geoip in 1.4 – the shortcut in django.contrib.gis.utils will be removed.
django.conf.urls.defaults will be removed. The functions include(), patterns() and url() plus handler404, handler500, are now available through django.conf.urls .
- [ ] The functions setup_environ() and execute_manager() will be removed from django.core.management. This also means that the old (pre-1.4) style of manage.py file will no longer work.
- [ ] Setting the is_safe and needs_autoescape flags as attributes of template filter functions will no longer be supported.
The attribute HttpRequest.raw_post_data was renamed to HttpRequest.body in 1.4. The backward compatibility will be removed – HttpRequest.raw_post_data will no longer work.
- [ ] The value for the post_url_continue parameter in ModelAdmin.response_add() will have to be either None (to redirect to the newly created object’s edit page) or a pre-formatted url. String formats, such as the previous default '../%s/', will not be accepted any more.

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;dmQOgwt9&#x2F;185-django-upgrade"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Django Upgrade</a>

**Comment by scottx611x** [comment]
#589

**Comment by scottx611x** [comment]
Closed with a4eb092d34a7ab8683e0c6b62bef0e549a80ae5c

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;dmQOgwt9&#x2F;185-django-upgrade"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Django Upgrade</a>
