### ISSUE TITLE
Provenance View: Sometimes Loading icon does not stop spinning

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#697]
### Reproduce (Sometimes)
1) On refinery dev site: Select a dataset (RFC Test) YOU OWN
2) Select display: provenance

### Observed
Loading icon continues, even though graph is loaded
<img width="1006" alt="screen shot 2015-09-16 at 10 06 13 am" src="https://cloud.githubusercontent.com/assets/9956764/9906953/dc3f8336-5c5a-11e5-84c9-5ca35551576d.png">

### Expected
The spinning icon to stop spinning when the graph is loaded.
When there is no graph, expect a message like "No graph available."

**Comment by jkmarx** [comment]
Console:
<img width="1224" alt="screen shot 2015-09-16 at 10 18 53 am" src="https://cloud.githubusercontent.com/assets/9956764/9907277/5c0df6f0-5c5c-11e5-916d-0d3b93a54fbf.png">

**Comment by flekschas** [comment]
For me the prov vis never even show up.

**Comment by sluger** [comment]
@flekschas can you give me an example dataset as well as console output where the provenance graph didn't show up?

It might also be a result of manually manipulating datasets, nodes, or analyses within the admin interface. I sometimes noticed this problem in the past after removing unsuccessful analyses. Though I thought I have fixed some of the problems, it seems there are some corner-cases in the initialization left. I most likely can't fix this is issue till Fairhaven milestone.

**Comment by flekschas** [comment]
This happens for datasets that I own and which I haven't shared with anybody. As I don't have access to the admin interface on https://refinery-dev.stemcellcommons.org I believe this issue is not related to manual data manipulations. I only have two own datasets on (_15416: Pseudo-temporal ordering of individual cells reveals regulators of differentiation_ and _16355: ChIP-Seq of Oct4 in Human Embryonic stem cells._) refinery-dev and for both the prov graph is not loading (without any error being thrown)

**Comment by ngehlenborg** [comment]
I observe the same issue. This is shown on the console:

![screen shot 2015-09-29 at 2 36 58 pm](https://cloud.githubusercontent.com/assets/1216518/10174457/d026479e-66b7-11e5-8dba-fbd701418907.png)
