### ISSUE TITLE
Investigate Solr deletion strategy

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#832]
We should investigate how Solr handles deleting documents. Related to #802 we had to optimize Solr to really delete node documents. We should figure out if optimizing is always needed because we delete objects from the index at other places too and it would be good to know when we need to optimize.

Nice explanation of how Solr works in relation to optimization:
http://stackoverflow.com/a/3737972/981933

Why optimizing often can be harmful:
http://stackoverflow.com/a/2141412/981933

**Comment by scottx611x** [comment]
Currently we are deleting objects from Solr indicies using the `remove_object` method here: 

* http://django-haystack.readthedocs.org/en/latest/searchindex_api.html?highlight=remove_object#SearchIndex.remove_object

Seen Here: 
* https://github.com/parklab/refinery-platform/blob/develop/refinery/core/utils.py#L577

Haystack's documentation on `remove_object` is pretty vague, and does not give any lead as to how an object is actually deleted.

**Comment by scottx611x** [comment]
__From__: https://wiki.apache.org/solr/FAQ#Why_doesn.27t_my_index_directory_get_smaller_.28immediately.29_when_i_delete_documents.3F_force_a_merge.3F_optimize.3F

__Why doesn't my index directory get smaller (immediately) when i delete documents? force a merge? optimize?__

- Because of the "inverted index" data structure, deleting documents only annotates them as deleted for the purpose of searching. The space used by those documents will be reclaimed when the segments they are in are merged.

- When segments are merged (either because of the Merge Policy as documents are added, or explicitly because of a forced merge or optimize command) then Solr attempts to delete old segment files, but on some filesystems Notably in Microsoft Windows) it is not possible to delete a file while the file is open for reading (Which is usually true since Solr is still serving requests against the old segments until the new Searcher is ready and has it's caches warmed). When this happens, the older segment files are left on disk, and Solr will re-attempt to delete them later the next time a merge happens.

**Comment by flekschas** [comment]
That sounds like object that have been marked as deleted should / are not be returned but Solr anymore?

I guess the question is whether we need to run optimize after every delete or just every other day or week.
