### ISSUE TITLE
Evaluate alternatives to PhantomJS

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#991]
Issues using PhantmJS: #988 and #989.

Potential alternatives:
* http://alternativeto.net/software/phantomjs/
* https://twolfson.com/2014-11-22-moving-from-phantomjs-to-node-webkit
* http://www.chrisle.me/2013/08/5-reasons-i-chose-selenium-over-phantomjs/
* http://sqa.stackexchange.com/questions/11973/alternative-to-selenium-phantomjs
* https://angular.github.io/protractor

**Comment by flekschas** [comment]
Just a note to avoid confusing:
- Selenium is not a browser, it operates on top of browser engines.
- Protractor is only a framework for end-to-end tests not for unit tests (that's what Karma is for). It can't replace PhantomJS.
- We can't just use any tool available because Karma needs to be able to launch the tests in the browser environment at least: we are limited to the following choices: https://www.npmjs.com/browse/keyword/karma-launcher
- We should evaluate the latest version of PhantomJS first
- Electron (formally known as atom-shell) might be an option. Also see here https://www.reddit.com/r/javascript/comments/3uuxvo/nwjs_vs_electron/

**Comment by flekschas** [comment]
Note: both issues were not caused by PhantomJS. (In order of increasing severity, the following parties are to be blamed: Grunt, Fritz, and Karma.)

**Comment by ngehlenborg** [comment]
Let's not worry about PhantomJS alternatives for now.
